import {
  Award,
  BarChart3,
  Bell,
  Blocks,
  Bot,
  BookOpen,
  Boxes,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChefHat,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Croissant,
  Dumbbell,
  Factory,
  FileCheck,
  Flame,
  FlaskConical,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  KeyRound,
  Laptop,
  Layers,
  Leaf,
  Lock,
  MapPin,
  Megaphone,
  MessageCircle,
  Package,
  Palette,
  PartyPopper,
  PencilRuler,
  Phone,
  Rocket,
  Ruler,
  Scissors,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Smile,
  Sofa,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Target,
  Timer,
  TrendingUp,
  Truck,
  Users,
  UserCheck,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icons a widget can name.
 *
 * The map this replaces held twelve, while the templates between them ask for
 * more than forty — so a coaching centre, a barber and a solar company all
 * showed the same lightning bolt. Everything the templates use is here, plus a
 * handful of obvious extras for anyone typing their own.
 *
 * Curated rather than importing all of Lucide: the whole set is thousands of
 * icons and would dwarf the rest of the bundle.
 */
export const iconMap: Record<string, LucideIcon> = {
  Award,
  BarChart3,
  Bell,
  Blocks,
  Bot,
  BookOpen,
  Boxes,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChefHat,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Croissant,
  Dumbbell,
  Factory,
  FileCheck,
  Flame,
  FlaskConical,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  KeyRound,
  Laptop,
  Layers,
  Leaf,
  Lock,
  MapPin,
  Megaphone,
  MessageCircle,
  Package,
  Palette,
  PartyPopper,
  PencilRuler,
  Phone,
  Rocket,
  Ruler,
  Scissors,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Smile,
  Sofa,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Target,
  Timer,
  TrendingUp,
  Truck,
  Users,
  UserCheck,
  Wrench,
  Zap,
}

/** Names offered in the properties panel, alphabetically. */
export const iconNames = Object.keys(iconMap).sort()

export function getIcon(name?: string): LucideIcon {
  if (!name) return Sparkles
  // Tolerate a name typed in lower case or with spaces.
  const key = Object.keys(iconMap).find(
    (candidate) => candidate.toLowerCase() === name.replace(/\s+/g, '').toLowerCase(),
  )
  return key ? iconMap[key] : Sparkles
}
